CREATE SEQUENCE IF NOT EXISTS usr_id_seq START WITH 1 INCREMENT BY 1;

create type role_type as enum ('ROLE_USER', 'ROLE_ADMIN');

CREATE TABLE IF NOT EXISTS user_roles
(
    user_id BIGINT    NOT NULL,
    role    VARCHAR(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS usr
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    owner_id BIGINT,
    CONSTRAINT usr_pkey PRIMARY KEY (id)
);

ALTER TABLE usr
    ADD CONSTRAINT usr_username_key UNIQUE (username);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES usr (id) ON DELETE CASCADE;

INSERT INTO user_roles (user_id, role)
SELECT id, 'ROLE_ADMIN'::role_type FROM usr WHERE username = 'admin'
ON CONFLICT DO NOTHING;