CREATE SEQUENCE IF NOT EXISTS pet_friends_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS pet_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS pet
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    birth_date  date,
    breed       VARCHAR(255),
    color       VARCHAR(255),
    tail_length INTEGER DEFAULT 0,
    owner_id    BIGINT                                NOT NULL,
    CONSTRAINT pet_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS pet_friends
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pet_id    BIGINT                                  NOT NULL,
    friend_id BIGINT                                  NOT NULL,
    CONSTRAINT pet_friends_pkey PRIMARY KEY (id)
);

ALTER TABLE pet_friends
    ADD CONSTRAINT unique_friendship UNIQUE (pet_id, friend_id);

ALTER TABLE pet_friends
    ADD CONSTRAINT fk_friend FOREIGN KEY (friend_id) REFERENCES pet (id) ON DELETE CASCADE;

ALTER TABLE pet_friends
    ADD CONSTRAINT fk_pet FOREIGN KEY (pet_id) REFERENCES pet (id) ON DELETE CASCADE;